go:
    # Whenever the Go version is updated here, .circle/config.yml and
    # .promu-cgo.yml should also be updated.
    version: 1.19
repository:
    path: github.com/prometheus/node_exporter
build:
    binaries:
        - name: node_exporter
    flags: -a -tags 'netgo osusergo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision=a954c9fea6bcccea7f68a77a002a2a878ef1d60c
        -X github.com/prometheus/common/version.Branch=https://github.com/zhangyichi2008/node_exporter.git
        -X github.com/prometheus/common/version.BuildUser=zhangyichi
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux
        - openbsd/amd64

